version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:3478@postgres-container:5432/strike_em_all
  postgres-server:
    image: postgres:latest
    container_name: postgres-container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: strike_em_all
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3478
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: