"""archive

Revision ID: 90fd286be40a
Revises: d8a4bacdf06b
Create Date: 2024-05-25 15:06:51.323814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90fd286be40a'
down_revision = 'd8a4bacdf06b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('releases', sa.Column('archive_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('releases', 'archive_path')
    # ### end Alembic commands ###
