"""a

Revision ID: d4da5f6d5e3c
Revises: 9dec5ece492b
Create Date: 2023-12-17 16:59:06.480083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4da5f6d5e3c'
down_revision = '9dec5ece492b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carts', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('price', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
